-- MySQL Script generated by MySQL Workbench
-- Sat Nov 23 18:39:56 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_crud
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_crud
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_crud` DEFAULT CHARACTER SET utf8 ;
USE `db_crud` ;

-- -----------------------------------------------------
-- Table `db_crud`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_crud`.`veiculo` (
  `id_veiculo` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(30) NOT NULL,
  `modelo` VARCHAR(30) NOT NULL,
  `placa` VARCHAR(8) NOT NULL,
  `final_placa` INT(1) NOT NULL,
  `data_compra` DATE NOT NULL,
  `seguro` ENUM('sim', 'nao') NOT NULL,
  `descricao` TEXT(200) NOT NULL,
  PRIMARY KEY (`id_veiculo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
